version: '3'
services:
  ansible:
    build: ./ansible
    tty: true
    working_dir: '/var/data'
    volumes:
      - ./ansible:/var/data
      - ./django:/var/data/app
  target01:
    build: ./target
    tty: true
    privileged: true
    command: /sbin/init
    ports:
      - 8999:80
