- name: install rsync
  yum:
    name: rsync

- name: djangoプロジェクトのディレクトリを作成
  file:
    group: "{{ service_group }}"
    mode: 0755
    owner: "{{ service_user }}"
    path: "{{ django_project_dest }}"
    state: directory

- name: djangoプロジェクトのデプロイ
  synchronize:
    checksum: yes
    delete: yes
    dest: "{{ django_project_dest }}/"
    recursive: yes
    src: "{{ django_project_from }}"

- name: djangoプロジェクトの権限の変更
  file:
    group: "{{ service_group }}"
    owner: "{{ service_user}}"
    path: "{{ django_project_dest }}"
    recurse: yes
    state: directory

- name: pip3を用いてrequirements.txtのインストール
  command: pip3 install -r requirements.txt chdir={{ django_project_dest }}/{{ django_project_name }}

- name: gunicornサービスのpid設定
  template:
    dest: '/etc/tmpfiles.d/gunicorn.conf'
    group: root
    owner: root
    src: 'templates/gunicorn.conf.j2'
  notify: 'systemd-tmpfiles changed'

- name: systemdのtmpfilesの変更
  command: /usr/bin/systemd-tmpfiles --create

- name: gunicornサービスのデプロイ
  template:
    dest: '/etc/systemd/system/gunicorn.service'
    group: root
    owner: root
    src: 'templates/gunicorn.service.j2'
  notify: 'gunicorn.service unitfile changed'

- name: gunicornサービスの再起動
  systemd:
    daemon_reload: yes
    name: 'gunicorn.service'
    state: restarted

- name: gunicornサービスの有効化
  systemd:
    enabled: yes
    name: 'gunicorn.service'
    state: started

- name: Nginxの仮想サイト設定をavailableに適応する
  template:
    dest: '/etc/nginx/sites-available/nginx.{{django_project_name}}.conf'
    src: 'templates/nginx.conf.j2'
  notify: 'nginx configuration changed'

- name: availableからenabledに移動する
  file:
    dest: '/etc/nginx/sites-enabled/nginx.{{django_project_name}}.conf'
    src: '/etc/nginx/sites-available/nginx.{{django_project_name}}.conf'
    state: link
  notify: 'nginx configuration changed'

- name: djangoのマイグレーション
  command: python3 manage.py migrate chdir={{ django_project_dest }}/app/{{ django_project_name }}

- name: 静的ファイルのデプロイ
  command: python3 manage.py collectstatic chdir={{ django_project_dest }}/app/{{ django_project_name }}
