- hosts: target
  name: nginx setup
  roles:
    - role: nginx

- hosts: target
  name: postgresql setup
  roles:
    - role: postgresql

- hosts: target
  name: python3 setup
  roles:
    - role: python3

- hosts: target
  name: deploy django
  roles:
    - role: django
